version: '3.0'

networks:
  debug:
    name: fabric_debug

services:

  ca.org1.debugger.com:
    image: hyperledger/fabric-ca:1.5
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=5054
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:15054
    working_dir: /etc/hyperledger/fabric/scripts
    ports:
      - "5054:5054"
      - "15054:15054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../../local/organizations/fabric-ca/org1:/etc/hyperledger/fabric-ca-server
      - ../../:/etc/hyperledger/fabric
    container_name: ca.org1.debugger.com
    networks:
      - debug